language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - nightly
before_script: 
  - cd application && php composer.phar install
script: 
  - php vendor/bin/phpcs app --standard=PSR2
  - php -d date.timezone=Europe/Paris vendor/bin/phpmd app text codesize,unusedcode,naming,design,controversial