---
- name: Prerequisites for provisioning
  sudo: yes
  apt:
    name: python-pycurl  # Ansible PPA module uses this
  tags:
    - deps
    - varnish
    - http-cache

- name: Add official APT repository
  sudo: yes
  register: _repo
  apt_repository:
    repo: "deb http://repo.varnish-cache.org/{{ansible_distribution|lower()}}/ {{ansible_distribution_release}} varnish-{{varnish_version}}"
  tags:
    - repo
    - varnish
    - http-cache

- name: Retrieve repo signing key
  sudo: yes
  register: _repo_key
  apt_key:
    url: "http://repo.varnish-cache.org/{{ansible_distribution|lower()}}/GPG-key.txt"
  tags:
    - repo
    - varnish
    - http-cache

- name: Update repository caches
  when: (_repo_key.changed or _repo.changed)
  sudo: yes
  apt: update_cache=yes
  tags:
    - repo
    - varnish
    - http-cache

- name: Install Varnish
  sudo: yes
  apt: name=varnish state=present
  tags:
    - deps
    - varnish
    - http-cache

- name: Create configuration directories
  sudo: yes
  file:
    dest: "{{item}}"
    state: directory
  with_items:
    - "{{varnish_vcl_dir}}"
  tags:
    - conf
    - varnish
    - http-cache

- name: Configure Varnish
  sudo: yes
  template:
    src: varnish.conf
    dest: "{{varnish_conf_file}}"
  notify: restart varnish
  tags:
    - conf
    - varnish
    - http-cache

- include: vcl.yml
  name: default
  state: present