---
- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: add timezone to /etc/timezone
  template: src=timezone dest=/etc/timezone owner=root group=root mode=0644
  when: ansible_date_time.tz != "CEST"
  notify: update timezone

- name: set server local
  locale_gen: name=fr_FR.UTF-8 state=present

- name: Install System Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: ["curl","wget","python-software-properties"]

- name: Install Extra Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: ["git","vim","pv","htop"]