---
   - name: img vhost setup
     template: src='img.conf' dest='/etc/nginx/sites-available'

   - name: img vhost enabled
     file: src=/etc/nginx/sites-available/img.conf dest=/etc/nginx/sites-enabled/img.conf state=link
     notify: restart nginx

   - name: composer install
     command: php composer.phar install
     args:
       chdir: /var/www/img